### ISSUE TITLE
Reading the microcode revision number would be nice

### ISSUE THREAD

**Issue by HenkPoley** [tycho/cpuid#9]
How Linux does it: https://github.com/torvalds/linux/blob/ead751507de86d90fa250431e9990a8b881f713c/arch/x86/include/asm/microcode_intel.h#L56

**Comment by tycho** [comment]
I think that can only be done via an MSR read, not via CPUID

On Jan 27, 2018 1:45 AM, "HenkPoley" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tycho/cpuid/issues/9>, or mute the thread

**Comment by tycho** [comment]
Going to close this since it's not really doable with CPUID...
